//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthee.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public int ActivityTypeID { get; set; }
        public int DoctorID { get; set; }
        public int StatusID { get; set; }
        public string Details { get; set; }
        public string Data { get; set; }
        public System.DateTime ActivityDate { get; set; }
    }
}
